version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: camera
      MYSQL_ROOT_PASSWORD: rangjin0342
      TZ: 'Asia/Seoul'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - server_network

  application:
    container_name: spring_server
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
      spring_jpa_hibernate_ddl-auto: none
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/camera?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rangjin0342
    depends_on:
      - database
    networks:
      - server_network

networks:
  server_network: